<bold>Exercise On Functions</bold>

In [ ]:
#Task01: Create a Python program that converts between different units of measurement.
def m_to_ft(meters):
    return meters * 3.280

def ft_to_m(feet):
    return feet / 3.280

def kg_to_lbs(kilogram):
    return kilogram * 2.204

def lbs_to_kg(pounds):
    return pounds / 2.204

def l_to_gal(liter):
    return liter * 0.2641

def gal_to_l(gallon):
    return gallon / 0.2641

def conversion():
    try:
        print("Choose a conversion type: ")
        print("1. Length")
        print("2. Weight")
        print("3. Volume")
        choice = int(input("Enter your choice (1-3): "))

        if choice == 1:
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            choice2 = int(input("Enter your choice (1-2): "))
            value = float(input("Enter your value to convert: "))
            if choice2 == 1:
                result = m_to_ft(value)
                print(f"{value}m = {result}ft")
            elif choice2 == 2:
                result = ft_to_m(value)
                print(f"{value}ft = {value}m")
            else:
                print("Invalid choice. Please try again!")

        elif choice == 2:
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            choice2 = int(input("Enter your choice (1-2): "))
            value = float(input("Enter your value to convert: "))
            if (choice2 == 1):
                result = kg_to_lbs(value)
                print(f"{value}kg = {result}lbs")
            elif (choice2 == 2):
                result = lbs_to_kg(value)
                print(f"{value}lbs = {result}kg")
            else:
                print("Invalid choice. Please try again!")

        elif choice == 3:
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")
            choice2 = int(input("Enter your choice (1-2): "))
            value = float(input("Enter your value to convert: "))
            if (choice2 == 1):
                result = l_to_gal(value)
                print(f"{value}l = {result}gal")
            elif (choice2 == 2):
                result = gal_to_l(value)
                print(f"{value}gal = {result}l")
            else:
                print("Invalid choice. Please try again!")

        else:
            print("Invalid input. Please try again!")

    except ValueError:
        print("Invalid input. Please enter a number.")

if __name__ == "__main__":
    conversion()

Choose a conversion type: 
1. Length
2. Weight
3. Volume
Enter your choice (1-3): k
Invalid input. Please enter a number.


In [ ]:
#Task02: Create a Python program that performs various mathematical operations on a list of numbers.
def calculate_sum(numbers):
    return sum(numbers)

def calculate_avg(numbers):
    return sum(numbers) / len(numbers) if numbers else 0

def find_max(numbers):
    return max(numbers)

def find_min(numbers):
    return min(numbers)

def main():
    try:
        print("Choose a mathematical operation:")
        print("1. Sum")
        print("2. Average")
        print("3. Maximum")
        print("4. Minimum")

        choice = int(input("Enter your choice (1-4): "))
        numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))

        if not numbers:
            print("Error: The list of numbers cannot be empty.")
            return

        if choice == 1:
            print(f"Sum: {calculate_sum(numbers)}")
        elif choice == 2:
            print(f"Average: {calculate_avg(numbers)}")
        elif choice == 3:
            print(f"Maximum: {find_max(numbers)}")
        elif choice == 4:
            print(f"Minimum: {find_min(numbers)}")
        else:
            print("Invalid choice.")
    except ValueError:
        print("Invalid input. Please enter numeric values.")

if __name__ == "__main__":
    main()


Choose a mathematical operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1-4): 4
Enter numbers separated by spaces: 1
Minimum: 1.0


Exercise on List Manipulation

In [ ]:
#Task01: Extract Every Other Element:
def extract_every_other(lst):
    return lst[::2]

def main():
    user_input = input("Enter elements separated by space: ").split()
    print(f"List:", user_input)
    print(f"Every other element in the list: {extract_every_other(user_input)}")

if __name__ == "__main__":
    main()

Enter elements separated by space: 1 2 3 4 5
List: ['1', '2', '3', '4', '5']
Every other element in the list: ['1', '3', '5']


In [ ]:
#Task02: Slice a Sublist
def get_sublist(lst, start, end):
    return lst[start:end+1]

def main():
    user_input = input("Enter elements separated by space: ").split()
    start = int(input("Enter start element: "))
    end = int(input("Enter end element: "))
    print(f"List:", user_input)
    print(f"Sliced Sublist: {get_sublist(user_input, start, end)}")

if __name__ == "__main__":
    main()

Enter elements separated by space: 1 2 3 4 5 6 
Enter start element: 2
Enter end element: 5
List: ['1', '2', '3', '4', '5', '6']
Sliced Sublist: ['3', '4', '5', '6']


In [ ]:
#Task03: Reverse a List Using Slicing:
def reverse_list(lst):
    return lst[::-1]

def main():
    user_input = input("Enter elements separated by space: ").split()
    print(f"List:", user_input)
    print(f"Reversed List: {reverse_list(user_input)}")

if __name__ == "__main__":
    main()

Enter elements separated by space: 1 2 3 4 5 6 
List: ['1', '2', '3', '4', '5', '6']
Reversed List: ['6', '5', '4', '3', '2', '1']


In [ ]:
#Task04: Remove the First and Last Elements:
def remove_first_last(lst):
    return lst[1:-1]

def main():
    user_input = input("Enter elements separated by space: ").split()
    print(f"List:", user_input)
    print(f"Removed first and last elements from list: {remove_first_last(user_input)}")

if __name__ == "__main__":
    main()

In [ ]:
#Task05: Get the First n Elements:
def get_first_n(lst, n):
    return lst[1:-1]

def main():
    user_input = input("Enter elements separated by space: ").split()
    n = int(input("Enter the number of elements to be displayed: "))
    print(f"List:", user_input)
    print(f"First {n} elements: {get_first_n(user_input, n)}")

main()

Enter elements separated by space: 12 4 5 
Enter the number of elements to be displayed: 1
List: ['12', '4', '5']
First 1 elements: ['4']


In [ ]:
#Task06: Extract Elements from the End:
def get_last_n(lst, n):
    return lst[-n:]

def main():
    user_input = input("Enter elements separated by space: ").split()
    n = int(input("Enter the number of elements to be displayed from last: "))
    print(f"List:", user_input)
    print(f"Every other element in the list: {get_last_n(user_input, n)}")

if __name__ == "__main__":
    main()

Enter elements separated by space: 89 0 7 5 
Enter the number of elements to be displayed from last: 2
List: ['89', '0', '7', '5']
Every other element in the list: ['7', '5']


In [ ]:
#Task07: Extract Elements in Reverse Order:
def reverse_skip(lst):
    return lst[-2::-2]

def main():
    user_input = input("Enter elements separated by space: ").split()
    print(f"List:", user_input)
    print(f"Elements in reverse order starting from second-to-last: {reverse_skip(user_input)}")

if __name__ == "__main__":
    main()

Exercise on Nested List:

In [ ]:
#Task01: Flatten a Nested List
def flatten(lst):
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)
    return flat_list

def main():
    x = int(input("Enter the number of sublists: "))
    list1 = []

    for i in range(x):
        y = int(input(f"Enter the number of elements in sublist {i+1}: "))
        sublist = []
        for j in range(y):
            sublist.append(input(f"Enter element {j+1} of sublist {i+1}: "))
        list1.append(sublist)

    print("Original Nested List:", list1)
    print("Flattened List:", flatten(list1))

if __name__ == "__main__":
    main()


Enter the number of sublists: 2
Enter the number of elements in sublist 1: 3
Enter element 1 of sublist 1: A
Enter element 2 of sublist 1: B
Enter element 3 of sublist 1: C
Enter the number of elements in sublist 2: 2
Enter element 1 of sublist 2: D 
Enter element 2 of sublist 2: C
Original Nested List: [['A', 'B', 'C'], ['D ', 'C']]
Flattened List: ['A', 'B', 'C', 'D ', 'C']


In [ ]:
#Task02: Accessing Nested List Elements
def access_nested_element(lst, indices):
    elem = lst
    for index in indices:
        elem = elem[index]
    return elem

def main():
    x = int(input("Enter the number of sublists: "))
    list1 = []

    for i in range(x):
        y = int(input(f"Enter the number of elements in sublist {i+1}: "))
        sublist = []
        for j in range(y):
            sublist.append(input(f"Enter element {j+1} of sublist {i+1}: "))
        list1.append(sublist)

    print("Original Nested List:", list1)

    indices = list(map(int, input("Enter indices separated by space: ").split()))

    try:
        print("Element at indices", indices, ":", access_nested_element(list1, indices))
    except IndexError:
        print("Error: Indices out of range!")

if __name__ == "__main__":
    main()


In [ ]:
#Task03: Sum of All Elements in a Nested List
def sum_nested(lst):
    return sum(flatten(lst))

def main():
    x = int(input("Enter the number of sublists: "))
    list1 = []

    for i in range(x):
        y = int(input(f"Enter the number of elements in sublist {i+1}: "))
        sublist = []
        for j in range(y):
            sublist.append(int(input(f"Enter element {j+1} of sublist {i+1}: ")))
        list1.append(sublist)

    print("Original Nested List:", list1)
    print("Sum of all elements:", sum_nested(list1))

if __name__ == "__main__":
    main()


In [ ]:
#Task04: Remove Specific Element from a Nested List
def remove_element(lst, elem):
    if isinstance(lst, list):
        return [remove_element(sublist, elem) for sublist in lst if sublist != elem]
    return lst if lst != elem else None

def clean_list(lst):
    if isinstance(lst, list):
        return [clean_list(item) for item in lst if item is not None]
    return lst

def main():
    x = int(input("Enter the number of sublists: "))
    list1 = []

    for i in range(x):
        y = int(input(f"Enter the number of elements in sublist {i+1}: "))
        sublist = []
        for j in range(y):
            sublist.append(int(input(f"Enter element {j+1} of sublist {i+1}: ")))
        list1.append(sublist)

    elem = int(input("Enter element to remove: "))
    modified_list = clean_list(remove_element(list1, elem))

    print("Original Nested List:", list1)
    print("Modified list:", modified_list)

if __name__ == "__main__":
    main()


In [ ]:
#Task05: Find the Maximum Element in a Nested List
def find_max(lst):
    return max(flatten(lst))

def main():
    x = int(input("Enter the number of sublists: "))
    list1 = []

    for i in range(x):
        y = int(input(f"Enter the number of elements in sublist {i+1}: "))
        sublist = []
        for j in range(y):
            sublist.append(int(input(f"Enter element {j+1} of sublist {i+1}: ")))
        list1.append(sublist)

    print("Original Nested List:", list1)
    print("Maximum element:", find_max(list1))

if __name__ == "__main__":
    main()

Enter the number of sublists: 2
Enter the number of elements in sublist 1: 1
Enter element 1 of sublist 1: 6
Enter the number of elements in sublist 2: 2
Enter element 1 of sublist 2: 1
Enter element 2 of sublist 2: 4
Original Nested List: [[6], [1, 4]]
Maximum element: 6


In [ ]:
#Task06: Count Occurrences of an Element in a Nested List
def count_occurrences(lst, elem):
    return flatten(lst).count(elem)

def main():
    x = int(input("Enter the number of sublists: "))
    list1 = []

    for i in range(x):
        y = int(input(f"Enter the number of elements in sublist {i+1}: "))
        sublist = []
        for j in range(y):
            sublist.append(int(input(f"Enter element {j+1} of sublist {i+1}: ")))
        list1.append(sublist)

    elem = int(input("Enter element to find: "))

    print("Original Nested List:", list1)
    print("Occurrences of element:", count_occurrences(list1, elem))

if
  main()

Enter the number of sublists: 1
Enter the number of elements in sublist 1: 2
Enter element 1 of sublist 1: 2
Enter element 2 of sublist 1: 1
Enter element to find: 2
Original Nested List: [[2, 1]]
Occurrences of element: 1


In [ ]:
#Task07: Flatten a List of Lists
def flatten(lst):
    """Recursively flattens a nested list."""
    flat_list = []
    for item in lst:
        if isinstance(item, list):  # Check if the item is a list
            flat_list.extend(flatten(item))  # Recursively flatten
        else:
            flat_list.append(item)  # Add non-list item directly
    return flat_list

def deep_flatten(lst):
    return flatten(lst)

def main():
    x = int(input("Enter the number of sublists: "))
    list1 = []

    for i in range(x):
        y = int(input(f"Enter the number of elements in sublist {i+1}: "))
        sublist = []
        for j in range(y):
            sublist.append(input(f"Enter element {j+1} of sublist {i+1}: "))
        list1.append(sublist)

    print("Original Nested List:", list1)
    print("Deep Flattened List:", deep_flatten(list1))

if __name__ == "__main__":
    main()


Enter the number of sublists: 2
Enter the number of elements in sublist 1: 1
Enter element 1 of sublist 1: 2
Enter the number of elements in sublist 2: 1
Enter element 1 of sublist 2: 3
Original Nested List: [['2'], ['3']]
Deep Flattened List: ['2', '3']


2

In [ ]:
#Task08: Nested List Average
def average_nested(lst):
    flat_list = flatten(lst)
    return sum(flat_list) / len(flat_list) if flat_list else 0

def main():
    x = int(input("Enter the number of sublists: "))
    list1 = []

    for i in range(x):
        y = int(input(f"Enter the number of elements in sublist {i+1}: "))
        sublist = []
        for j in range(y):
            sublist.append(int(input(f"Enter element {j+1} of sublist {i+1}: ")))
        list1.append(sublist)

    print("Original Nested List:", list1)
    print("Average of elements:", average_nested(list1))


main()



Basic Vector and Matrix Operation with Numpy

In [ ]:
import numpy as np
# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty Array (2x2):\n", empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\n2. All Ones Array (4x2):\n", ones_array)

# 3. Return a new array of given shape and type, filled with a fill value
fill_value_array = np.full((3, 3), 7)
print("\n3. Array filled with 7 (3x3):\n", fill_value_array)

# 4. Return a new array of zeros with the same shape and type as a given array
reference_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(reference_array)
print("\n4. Zeros Array with Same Shape as Reference Array:\n", zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(reference_array)
print("\n5. Ones Array with Same Shape as Reference Array:\n", ones_like_array)

# 6. Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n6. Converted NumPy Array:\n", numpy_array)


1. Empty Array (2x2):
 [[-2.    1.  ]
 [ 1.75 -0.75]]

2. All Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with 7 (3x3):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros Array with Same Shape as Reference Array:
 [[0 0]
 [0 0]]

5. Ones Array with Same Shape as Reference Array:
 [[1 1]
 [1 1]]

6. Converted NumPy Array:
 [1 2 3 4]


In [ ]:

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty Array (2x2):\n", empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\n2. All Ones Array (4x2):\n", ones_array)

# 3. Return a new array of given shape and type, filled with a fill value
fill_value = 5
filled_array = np.full((3, 3), fill_value)
print("\n3. Array filled with", fill_value, "(3x3):\n", filled_array)

# 4. Return a new array of zeros with the same shape and type as a given array
reference_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(reference_array)
print("\n4. Zeros Array with Same Shape as Reference Array:\n", zeros_like_array)

# 5. Return a new array of ones with the same shape and type as a given array
ones_like_array = np.ones_like(reference_array)
print("\n5. Ones Array with Same Shape as Reference Array:\n", ones_like_array)

# 6. Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n6. Converted NumPy Array:\n", numpy_array)


1. Empty Array (2x2):
 [[2.12199579e-314 7.02380607e-312]
 [5.41495948e-321 7.02380607e-312]]

2. All Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with 5 (3x3):
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

4. Zeros Array with Same Shape as Reference Array:
 [[0 0]
 [0 0]]

5. Ones Array with Same Shape as Reference Array:
 [[1 1]
 [1 1]]

6. Converted NumPy Array:
 [1 2 3 4]


In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("Addition of x and y:\n", add_xy)

# 2. Subtract the two arrays
sub_xy = x - y
print("\nSubtraction of x and y:\n", sub_xy)

# 3. Multiply the array x with any integer (e.g., 3)
mult_x = x * 3
print("\nMultiplication of x with 3:\n", mult_x)

# 4. Find the square of each element of x
square_x = x ** 2
print("\nSquare of each element of x:\n", square_x)

# 5. Dot product calculations
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("\nDot product of v and w:", dot_vw)
print("\nDot product of x and v:\n", dot_xv)
print("\nDot product of x and y:\n", dot_xy)

# 6. Concatenation
concat_xy_row = np.concatenate((x, y), axis=0)  # Along rows
concat_vw_col = np.vstack((v, w))  # Along columns

print("\nConcatenation of x and y along rows:\n", concat_xy_row)
print("\nConcatenation of v and w along columns:\n", concat_vw_col)

# 7. Concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)  # Attempting to concatenate x and v
    print("\nConcatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("\nError while concatenating x and v:", e)
    print("Reason: x has shape (2,2) and v has shape (2,). Their dimensions are incompatible for direct concatenation.")


Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x with 3:
 [[ 3  6]
 [ 9 15]]

Square of each element of x:
 [[ 1  4]
 [ 9 25]]

Dot product of v and w: 219

Dot product of x and v:
 [29 77]

Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]

Error while concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Reason: x has shape (2,2) and v has shape (2,). Their dimensions are incompatible for direct concatenation.


In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)

identity_matrix = np.dot(A, A_inv)

print("A * A_inv:\n", identity_matrix)
print("\nIdentity Matrix:\n", np.eye(2))  # Expected identity matrix


A * A_inv:
 [[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]

Identity Matrix:
 [[1. 0.]
 [0. 1.]]


In [ ]:
AB = np.dot(A, B)
BA = np.dot(B, A)

print("\nAB:\n", AB)
print("\nBA:\n", BA)
print("\nAre AB and BA equal?", np.array_equal(AB, BA))


AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

Are AB and BA equal? False


In [ ]:
AB_T = np.transpose(AB)

BT = np.transpose(B)
AT = np.transpose(A)
BT_AT = np.dot(BT, AT)

print("\n(AB)^T:\n", AB_T)
print("\nB^T * A^T:\n", BT_AT)
print("\nAre (AB)^T and B^T * A^T equal?", np.array_equal(AB_T, BT_AT))



(AB)^T:
 [[23 51]
 [13 29]]

B^T * A^T:
 [[23 51]
 [13 29]]

Are (AB)^T and B^T * A^T equal? True


In [ ]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("\nSolution for (x, y, z):\n", X)



Solution for (x, y, z):
 [ 2.  1. -2.]


In [ ]:
import numpy as np
import time

# 1. Element-wise Addition
size = 1_000_000

# Generate lists and arrays
list1 = list(range(size))
list2 = list(range(size))

array1 = np.arange(size)
array2 = np.arange(size)

# Using Python lists
start_time = time.time()
list_addition = [list1[i] + list2[i] for i in range(size)]
end_time = time.time()
print("Time taken for element-wise addition using lists:", end_time - start_time, "seconds")

# Using NumPy arrays
start_time = time.time()
array_addition = array1 + array2
end_time = time.time()
print("Time taken for element-wise addition using NumPy:", end_time - start_time, "seconds")


# 2. Element-wise Multiplication

# Using Python lists
start_time = time.time()
list_multiplication = [list1[i] * list2[i] for i in range(size)]
end_time = time.time()
print("\nTime taken for element-wise multiplication using lists:", end_time - start_time, "seconds")

# Using NumPy arrays
start_time = time.time()
array_multiplication = array1 * array2
end_time = time.time()
print("Time taken for element-wise multiplication using NumPy:", end_time - start_time, "seconds")


# 3. Dot Product

# Using Python lists
start_time = time.time()
dot_product_list = sum(list1[i] * list2[i] for i in range(size))
end_time = time.time()
print("\nTime taken for dot product using lists:", end_time - start_time, "seconds")

# Using NumPy arrays
start_time = time.time()
dot_product_numpy = np.dot(array1, array2)
end_time = time.time()
print("Time taken for dot product using NumPy:", end_time - start_time, "seconds")


# 4. Matrix Multiplication
matrix_size = 1000

# Generate matrices
matrix1_list = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]
matrix2_list = [[i - j for j in range(matrix_size)] for i in range(matrix_size)]

matrix1_np = np.array(matrix1_list)
matrix2_np = np.array(matrix2_list)

# Using Python lists
start_time = time.time()
result_matrix_list = [[sum(matrix1_list[i][k] * matrix2_list[k][j] for k in range(matrix_size))
                       for j in range(matrix_size)] for i in range(matrix_size)]
end_time = time.time()
print("\nTime taken for matrix multiplication using lists:", end_time - start_time, "seconds")

# Using NumPy arrays
start_time = time.time()
result_matrix_np = np.dot(matrix1_np, matrix2_np)
end_time = time.time()
print("Time taken for matrix multiplication using NumPy:", end_time - start_time, "seconds")


Time taken for element-wise addition using lists: 0.12043452262878418 seconds
Time taken for element-wise addition using NumPy: 0.002006053924560547 seconds

Time taken for element-wise multiplication using lists: 0.12220430374145508 seconds
Time taken for element-wise multiplication using NumPy: 0.0020051002502441406 seconds

Time taken for dot product using lists: 0.08339452743530273 seconds
Time taken for dot product using NumPy: 0.0 seconds

Time taken for matrix multiplication using lists: 121.48354887962341 seconds
Time taken for matrix multiplication using NumPy: 0.5948615074157715 seconds
